### ISSUE TITLE
Customising the width

### ISSUE THREAD

**Issue by spiro-stathakis** [2amigos/yii2-file-upload-widget#101]
Is there a way to customize the width of the upload form without losing the changes on update? 
I would like to set the width from 
div class="col-lg-7"
to 
div class="col-lg-12"

in  src/views/forms.php

**Comment by tonydspaniard** [comment]
You need to configure your own form view, and then tell the widget where to view for that new view on its `formView` attribute: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/FileUploadUI.php#L48
