### ISSUE TITLE
Uploading silently 

### ISSUE THREAD

**Issue by spiro-stathakis** [2amigos/yii2-file-upload-widget#102]
I would like to remove the feedback from the upload widget and instead update a gridview which  should show the newly uploaded files. Is there a way to do that with the Javascript callbacks ? 

Thanks

**Comment by tonydspaniard** [comment]
Yes, use `FileUpload` instead of `FileUploadUI` and then use the events to write your logic to update the grid: 

```php 
'clientEvents' => [
        'fileuploaddone' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
        'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
    ],
