### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vodanh86** [2amigos/yii2-file-upload-widget#103]
When I used FileUploadUI with this detail:

```php 
    <?= FileUploadUI::widget([
        'model' => $model,
        'attribute' => 'question_img',
        'url' => ['media/upload', 'id' => $model->id],
        'gallery' => false,
        'fieldOptions' => [
            'accept' => 'image/*'
        ],
        'clientOptions' => [
            'maxFileSize' => 2000000
        ],
        // ...
        'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
        ],
    ]); ?>
```
after uploading, I get error message:
**SyntaxError: Unexpected token < in JSON at position 0**. Can you help me to check

**Comment by tonydspaniard** [comment]
@vodanh86 I need further information, do you mind sharing the error log?

**Comment by tonydspaniard** [comment]
@vodanh86 I am going to close this issue as there is no further info given. For me the `clientOptions` is fine which is the only part that the library does json encoding. 

Is the error when uploading? when rendering? If you answer I'll reopen the issue.

**Comment by newscloud** [comment]
I'm also getting this error

SyntaxError: Unexpected token < in JSON at position 0

I've been working on this several hours. I agree with others. While we appreciate you offering a plugin, the examples are not sufficient.

**Comment by blarney2000** [comment]
This error usually comes from receiving an html response rather than an json response. This is often due to error reporting, which is done in HTML.
