### ISSUE TITLE
FileUpload: event 'fileuploadprocessstart' not working ... (other events work fine).

### ISSUE THREAD

**Issue by gvanto** [2amigos/yii2-file-upload-widget#108]
```
'clientEvents' => [
                        'fileuploadprocessstart' => 'function(e) {
                                console.log(\'fileuploadprocessstart\');
                                console.log(e);
                                
                            }  ',```

Gives nothing in console ...

**Comment by tonydspaniard** [comment]
@gvanto that event doesn't exist. You need to use `fileuploadstart` or any of the ones exposed on this link: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#callback-options

**Comment by gvanto** [comment]
Ah ok that works, thanks @tonydspaniard  !

Btw In the readme (code example) the link is pointing to: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options   (note: 'processing' is extra)
