### ISSUE TITLE
preview pdf

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#113]
Is it possible to preview the pdf to be uploaded ?
I used to use kartik fileuploader : http://demos.krajee.com/widget-details/fileinput
I like your interface better, but i love the pdf previewer... any suggesitons

**Comment by tonydspaniard** [comment]
This are two totally different plugins. Kartik evolved from a copy of Jasny components and this is pure blueimp. Nevertheless, there is a way to do what you wish as Kartik uses blob data, but you'll have to code it yourself. Here is an example with images: http://jsfiddle.net/Fractaliste/LvsYc/1669/

**Comment by tonydspaniard** [comment]
Here is how kartik's changes from data:uri to blob: https://github.com/kartik-v/bootstrap-fileinput/blob/master/js/fileinput.js#L157
