### ISSUE TITLE
Combining chunks into one file

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#114]
When i upload a large file with the chunks set I get a bunch of files on my server. How do I combine them back into one large file ?

**Comment by tonydspaniard** [comment]
Here you have an example server side file to combine them: https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php

**Comment by robov** [comment]
THANKS !!! Sorry I missed that.

**Comment by robov** [comment]
I went through that source. but I cannot seem to find where they combine the chunks into one file.
My files could be quite large (10gb, hence I am using your work) ... so I cannot combine them in memory and save... or is it just read, append, read append, etc...

**Comment by robov** [comment]
it is almost solved... reading and appending did the trick
The thing that I have not solved yet is how do stich using the correct filename
ie:
* each chunk calls the upload, and uploads only that chunk
* The only way I know what the 'to stitch to' filename is is by the name of the file and the session id
* filename only would be problems when multiple users upload the same file

Question
Is there an Identified for each file that is unique ? (for each file, not each chunk)

**Comment by robov** [comment]
would be nice if there was a unique id for every file being uploaded

**Comment by robov** [comment]
The problem I have right now is that when the uploadhandler is called then I only know the filename
But I do not know if this is 
* A) a chunk of a previous file
* B) a new file
