### ISSUE TITLE
Small screen design

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#115]
When I show the ui on a small screen (ie phone) then the design is not responsive
because of the fixed table layout of the list of files to be uploaded

Another thing I noticed when I was trying to edit the list template, then when I moved the progress bar to the filename column, I got a bunch of errors.

**Comment by tonydspaniard** [comment]
Hi @robov thank you very much for your feedback. 

The widget comes with the demo provided by jquery plugin. Nevertheless, you can easily modify them: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/FileUploadUI.php#L48

**Comment by robov** [comment]
YEs I found out how to modify it, but the downloadTemplateView template is a set of rows, so your code forces it to be a table (which is not responsive)

and...
Another thing I noticed when I was trying to edit the list template, then when I moved the progress bar to the filename column, I got a bunch of errors.

**Comment by tonydspaniard** [comment]
> YEs I found out how to modify it, but the downloadTemplateView template is a set of rows, so your code forces it to be a table (which is not responsive)

You simply need to add your download template: https://github.com/2amigos/yii2-file-upload-widget/blob/691d222dd01c642562bbe25cdb4182217e43a6f2/src/FileUploadUI.php#L56 

And if its a different template id, simply modify it here: 
https://github.com/2amigos/yii2-file-upload-widget/blob/59d7657548711c50282d931fdb125be5b68b5efc/src/FileUploadUI.php#L44

**Comment by robov** [comment]
but then it is still encapsulated in a table...
AHA.... I found it
the TABLE is defined in the formview... so I probably need to remove that to move to a div set
