### ISSUE TITLE
fieldOptions-accept not working well

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#116]
When I limit the fieldoptions to accept only pdf I get a file select limitation (I can only select pdf from my computer), however when I type in a name xx.zip.. then I can still upload that zip file.
The demo on blueimp has somewhere a check before the upload and prevents uploading the wrong filetype

**Comment by tonydspaniard** [comment]
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#acceptfiletypes

**Comment by robov** [comment]
Thanks...yes I found that but how do I set that in your widget settings ?

**Comment by robov** [comment]
And there seems to be alot of validation going on in the bluimp uploadhandler that is missing in your demo implementation... https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php

**Comment by tonydspaniard** [comment]
> And there seems to be alot of validation going on in the bluimp uploadhandler that is missing in your demo implementation...

The upload handler of jquery file upload certainly doesn't use Yii2 validation capabilities. We need to combine both. 

> Thanks...yes I found that but how do I set that in your widget settings ?

Everything on the plugin documentation can be set throughout `clientOptions`.  In fact, `clientOptions` transforms to the plugin configuration.




Thanks...yes I found that but how do I set that in your widget settings ?
--

**Comment by robov** [comment]
Cool... I could assume that , but I could not find it.

**Comment by robov** [comment]
when I set it:
```
    'clientOptions' => [
        'maxFileSize' => 10000 * $FilesizeGB ,
        'maxChunkSize' => 1 * $FilesizeMB,
        'maxNumberOfFiles' => 2,    
        'acceptFileTypes' => '/(\.|\/)(gif|jpe?g|png)$/i',
    ],
```
I get
```
Uncaught TypeError: options.acceptFileTypes.test is not a function
```

**Comment by tonydspaniard** [comment]
@robov you need to setup a valid regular expression. Therefore you need to use `new JsExpression`: 

```php 
'clientOptions' => [
        'maxFileSize' => 10000 * $FilesizeGB ,
        'maxChunkSize' => 1 * $FilesizeMB,
        'maxNumberOfFiles' => 2,    
        'acceptFileTypes' => new JsExpression('/(\.|\/)(gif|jpe?g|png)$/i'),
    ],

**Comment by robov** [comment]
AWESOME... thank you so much please include that in your demo, so other people won't have to struggle finding it....

**Comment by tonydspaniard** [comment]
> AWESOME... thank you so much please include that in your demo, so other people won't have to struggle finding it....

PRs are always welcome
