### ISSUE TITLE
Init plugin with DB values

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#117]
When my page loads I would like to show the list of the items already in the database. How do I show the list on a page load ?

**Comment by robov** [comment]
For all that have the same issue... here is the solution.
Place this js AFTER the echo of the widget, otherwise you get errors of calling before initialization
```
$.ajax({
    url: 'freepost/initlist',
    dataType: 'json',
    context: $('#dstransfersender-image-fileupload')[0]
}).done(function (init_data) 
{
    var form = $('#dstransfersender-image-fileupload');
    form.fileupload('option', 'done').call(form, $.Event('done'), {result: init_data}); 
});    

```

**Comment by tonydspaniard** [comment]
Thanks for the information @robov . I normally do show the already uploaded files with a partial view or a different section, where user can CRUD images at will. Your solution is good too. Thanks again.
