### ISSUE TITLE
CDN / minified

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#119]
How do I load the js / css assets in a minified version or better yet... from a CDN ?

**Comment by tonydspaniard** [comment]
You need to override the Asset Bundle provided and include your very own CDN links to the assets.

**Comment by robov** [comment]
Ok, how do I override that asset bundle ?
so that is uses mine instead of yours?

**Comment by tonydspaniard** [comment]
By extending the widget you use and override its registerClientScript method: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/FileUpload.php#L63

**Comment by robov** [comment]
Ok, thanks... I hoped you had a better way than extending and overwriting that method...

**Comment by tonydspaniard** [comment]
> Ok, thanks... I hoped you had a better way than extending and overwriting that method...

Nope, thats the regular way of doing it afaik.
