### ISSUE TITLE
Help needed with impleementing sorting to preview items.

### ISSUE THREAD

**Issue by Sonit90** [2amigos/yii2-file-upload-widget#123]
Hey, guys. Your widged works great, but i need sorting\arranging functionality. I understood, that this widges uses jquery template engine to generate html code. And i found quite simple widget, that can handle drag and drop: https://github.com/kartik-v/yii2-sortable-input But sorting widget needs a php array of items to work, that i can't generate, because template is in javascript. Any ideas how to make it work? Thanks in advance!

**Comment by tonydspaniard** [comment]
@Sonit90 I would do the following: When all uploads are finished, I would (using javascript) get the elements rendered and sort them. 

Use the `fileuploaddone` callback: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#callback-options
