### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by robov** [2amigos/yii2-file-upload-widget#127]
When I upload a big file (with many chunk) then the upload counter pauses on writing chunks to disk. This is ofcourse normal behavior, but because of the stop in counter and no change in the visual appearance the user might interpret this as a stalling of the system
So it would be nice if there was a chang in UI... something like
```
writing to disk... please hold ...
```
and maybe a simple animation like the dots  after hold (one dot - pause - 2 dots - 3 dots)
At least the user is aware that there is still activity

I am now testing uploading a 4 G file with 20MB chunks and the pausing of the UI sometimes takes quite long ()...

**Comment by tonydspaniard** [comment]
Hi @robov, 

Whilst I believe is a good idea. The widget is trying to simplify the use of the jquery plugin. I made many mistakes in the past trying to enhance the plugin itself and its maintenance became a nightmare. 

To be honest with you, if you plan to upload such big files, I would do it differently and is by using its progress upload event: https://github.com/blueimp/jQuery-File-Upload/wiki/Extended-progress-information 

That way your user will be up to date on what is going on...

**Comment by robov** [comment]
Thanks... and thank you for such amazing work...
