### ISSUE TITLE
French translation for "Select file..." missing

### ISSUE THREAD

**Issue by bluezed** [2amigos/yii2-file-upload-widget#130]
https://github.com/2amigos/yii2-file-upload-widget/blob/2fd078f589d4acdd2cbfb70eea88d526480b0102/src/messages/fr/fileupload.php#L28

**Comment by tonydspaniard** [comment]
PR requests highly appreciated :)

**Comment by bluezed** [comment]
I totally would but don't speak any French. If someone can tell me the correct translation I'll do a PR ;)

**Comment by tonydspaniard** [comment]
@bluezed hahahaha... I don't have a clue either.  I need to update the translation files anyway. I do my best.

**Comment by machour** [comment]
there you go fellas!
