### ISSUE TITLE
How to Upload ,Delete works in yii2

### ISSUE THREAD

**Issue by kapilmyakal** [2amigos/yii2-file-upload-widget#154]
Please give Full example so we can understand

**Comment by kapilmyakal** [comment]
Anyone Suggest me how Upload with progress in yii2.

**Comment by tonydspaniard** [comment]
@kapilmyakal the fileupload progress is actually handled by the plugin itself. The documentation is on their page: https://github.com/blueimp/jQuery-File-Upload/wiki/Extended-progress-information 

What you do is to configure the event as explained on the documentation and use the `data.bitrate` to update your html code using css or js.
