### ISSUE TITLE
Hidden field

### ISSUE THREAD

**Issue by rptts** [2amigos/yii2-file-upload-widget#16]
This widget is creating an input of type=hidden, but it seems a little unnecessary and its causing me some confusion of its purpose. 

Wouldn't the input with the type=file enough? I mean... none of the demos of the blueimp have the type=hidden input.

Cheers.

**Comment by tonydspaniard** [comment]
Will have a look when revisiting for http://yiiwheels.com standards.

**Comment by tonydspaniard** [comment]
Where is the hidden input displayed?

**Comment by rptts** [comment]
In my view I use:
```
<?= FileUpload::widget([
    'model' => $model,
    'attribute' => $attributeName,
    'url' => ['view', 'id' => $model->id],
    'options' => ['accept' => 'image/*'],
    'plus' => true,
    'clientOptions' => [
        'dropZone' => ".thumb-drop",
        'multiple' => false,
        'maxNumberOfFiles' => 1,
        'autoUpload' => false,
        'previewMaxWidth' => 148,
        'previewMaxHeight' => 148,
        'previewCrop' => true,
        'maxFileSize' => 2000000
    ],
]);?>
```

And when I inspect the element I've got
![hidden_input](https://cloud.githubusercontent.com/assets/1150267/7534271/f562e67e-f570-11e4-8241-bf08b9b72891.jpg)

**Comment by tonydspaniard** [comment]
Thats how Yii knows if a new file has been inserted or not: https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1277 

Not related to the widget

**Comment by rptts** [comment]
I see... My bad, thanks for your time!
