### ISSUE TITLE
Unable to use this widget

### ISSUE THREAD

**Issue by nvshivakumar** [2amigos/yii2-file-upload-widget#18]
Hi,

Plz provide tutorial

**Comment by tonydspaniard** [comment]
Tutorial on what? The rendering is done. You meant how to save the uploaded file?

**Comment by nvshivakumar** [comment]
No,
We are visualizing widget buttons.
But unable to add actions like, when we use "add button" to add files it is
showing in tooltop but not rendering below the widget  which has given in
demo

**Comment by tonydspaniard** [comment]
@nvshivakumar will try to write a blog post on it... but i'll require some time
