### ISSUE TITLE
Uploaded successfully but does not appear to be photos

### ISSUE THREAD

**Issue by hphuoclam** [2amigos/yii2-file-upload-widget#19]
Hi!
When pressing start, the image is saved on server, but when uploaded successfully it does not show up image. error SyntaxError: Unexpected token <.
I think not find the link that contains the image. Please help for me to edit the link contains photos

**Comment by tonydspaniard** [comment]
Please show the code of your uploader

**Comment by hphuoclam** [comment]
Hi! 
My code()

       public function actionUpload() {

        $model = new \frontend\modules\blog\models\Upload();

        if ($model->load(Yii::$app->request->post())) {

            $image = \yii\web\UploadedFile::getInstance($model, 'image');

            $path = Yii::$app->basePath . '/web/upload/' . $image->name;

            $response = [];

            $image->saveAs($path);

            echo JSON::encode([

                $response['files'][] = [

            'name' => $image->name,

            'type' => $image->type,

            'size' => $image->size,

            'thumbnailUrl' => '/upload/' . $image->name,

            ]]);

            Yii::$app->end();

        }

        return $this->render('upload', ['model' => $model]);

    }

I do not understand   <code>'thumbnailUrl'</code>  to display after successfully uploaded.

![ac](https://cloud.githubusercontent.com/assets/8954963/6649920/676daedc-ca2b-11e4-9c06-982382d97bc4.jpg)

**Comment by tonydspaniard** [comment]
@hphuoclam you have an error on your code. You should not `echo` the response, you need to `return` the JSON response and make sure the response is `json`:

```php 
Yii::$app->response->getHeaders()->set('Vary', 'Accept');
Yii::$app->response->format = Response::FORMAT_JSON;

return [
   'files' => [
       [
         // [...]
         'thumbnailUrl' => 'the url to the file that is going to be displayed as thumbnail' //
       ]
   ]
]; 

```

This is a working example of the action in a life project: 

```php 
public function actionUpload($id)
    {
        $tour = Tour::findOne($id);
        if (!$tour) {
            throw new NotFoundHttpException(Yii::t('app', 'Page not found'));
        }
        $picture = new TourPicture(['scenario' => 'upload']);
        $picture->tour_id = $id;
        $picture->image = UploadedFile::getInstance($picture, 'image');
        if ($picture->image !== null && $picture->validate(['image'])) {

            Yii::$app->response->getHeaders()->set('Vary', 'Accept');
            Yii::$app->response->format = Response::FORMAT_JSON;

            $response = [];

            if ($picture->save(false)) {
                $response['files'][] = [
                    'name' => $picture->image->name,
                    'type' => $picture->image->type,
                    'size' => $picture->image->size,
                    'url' => $picture->getImageUrl(),
                    'thumbnailUrl' => $picture->getImageUrl(TourPicture::SMALL_IMAGE),
                    'deleteUrl' => Url::to(['delete', 'id' => $picture->id]),
                    'deleteType' => 'POST'
                ];
            } else {
                $response[] = ['error' => Yii::t('app', 'Unable to save picture')];
            }
            @unlink($picture->image->tempName);
        } else {
            if ($picture->hasErrors(['picture'])) {
                $response[] = ['error' => HtmlHelper::errors($picture)];
            } else {
                throw new HttpException(500, Yii::t('app', 'Could not upload file.'));
            }
        }
        return $response;
    }
```

I also recommend you to have two actions:

- one exclusively for rendering 
- another to handle uploads

**Comment by hphuoclam** [comment]
thank you for helping me this issue

**Comment by alejofonseca** [comment]
Hi there,

Could you please share the code for TourPicture model?

Thank you.
