### ISSUE TITLE
Doesn't work in ActiveForm widget

### ISSUE THREAD

**Issue by ldjbenben** [2amigos/yii2-file-upload-widget#20]
the widget renders all buttons and the browse button functions, however the gallery doesn't populate when you select a file.

```php 
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\fileupload\FileUploadUI;

/* @var $this yii\web\View */
/* @var $model app\models\VoteItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vote-item-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= Html::activeHiddenInput($model, 'vid')?>
    
    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
    
	<?= FileUploadUI::widget([
	    'model' => $model,
	    'attribute' => 'litpic',
	    'url' => ['media/upload', 'id' => $model->id],
	    'gallery' => true,
	    'fieldOptions' => [
	            'accept' => 'image/*'
	    ],
	    'clientOptions' => [
	            'maxFileSize' => 2000000
	    ],
	    // ... 
	    'clientEvents' => [
	            'fileuploaddone' => 'function(e, data) {
	                                    console.log(e);
	                                    console.log(data);
	                                }',
	            'fileuploadfail' => 'function(e, data) {
	                                    console.log(e);
	                                    console.log(data);
	                                }',
	    ],
	]);
	?>

    <?= $form->field($model, 'desc')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
```

**Comment by tonydspaniard** [comment]
Will check when revisiting the extension for its usage on http://yiiwheels.com

**Comment by tonydspaniard** [comment]
@ldjbenben I think your approach is wrong. I wouldn't use this widget to fill a gallery that is NOT yet created. This extension is best used for batch uploading pictures for already created entities. 

For a picture in a form, I would rather use https://github.com/2amigos/yii2-file-input-widget

**Comment by bhanuagarwal** [comment]
Hi tonydspaniard ,
i want to know when i delete an image its deleted successfully but its shows there , how to use response from delete that it would not displayed.

**Comment by dmvslv** [comment]
@tonydspaniard I have the same issue. For example: I need implement create/update functionality for News with image gallery. I think we can add option which switch form/div tags.
Also we can add option which allow loads existing images. This functionality has implemented in blueimp file upload extension for Yii 1 https://github.com/Asgaroth/xupload and in blueimp widget demo script https://github.com/blueimp/jQuery-File-Upload/blob/master/js/main.js#L59. I can make pull request if you think that functionality is ok https://github.com/dmvslv/yii2-file-upload-widget/commit/0185f17fa2ef5c0e0b81f15f623c83791756739b

**Comment by tonydspaniard** [comment]
@creocoder is this something you can handle? I know you have updated the library

**Comment by tonydspaniard** [comment]
Thanks @dmvslv @creocoder will have a look at it. He had reviewed/refactored the extension and let me know if is all fine to merge.

**Comment by tonydspaniard** [comment]
Guys, do you mind trying with latest dev-master branch?

**Comment by hexl** [comment]
You can fix it by editing the form view. do not use the form tag.

**Comment by tonydspaniard** [comment]
@ldjbenben This was fixed https://github.com/2amigos/yii2-file-upload-widget/commit/ad8a40965b5c92eeae07c78bbc6124afe43f7eb1#diff-8e77a33e5212742de3ec4586df424a79L8 on latest merge, is on master. Will soon update version.
