### ISSUE TITLE
Load previously uploaded images

### ISSUE THREAD

**Issue by Inttegrum** [2amigos/yii2-file-upload-widget#21]
Is it possible?

I mean. Every time I reload the page all the uploaded images are gone and I can't know what I've uploaded already. I'm looking for something like this so I can also delete older images. I've been playing with 'gallery' => true but with the lack of documentation I'm not sure how this works.

**Comment by tonydspaniard** [comment]
What I do is that I go to a section where I do not only upload new but also display previously uploaded (when on loading/rendering the view). 

This way, if a user reloads the page it will still display previously uploaded files :)

**Comment by Inttegrum** [comment]
I know what you mean. I've been doing that for a while now but I was thinking on reusing the widget delete button to delete them.

I'll do that. Thanks.

**Comment by tonydspaniard** [comment]
I do not believe is supported.
