### ISSUE TITLE
BlueImp File Upload Widget for Yii2 error yii2

### ISSUE THREAD

**Issue by sunnybhakta** [2amigos/yii2-file-upload-widget#25]
I am working with BlueImp File Upload Widget for Yii2 but i am getting SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data error . How can i solve this thanks.

Here is screenshort for that http://awesomescreen....com/0ab4tc1wd0

**Comment by tonydspaniard** [comment]
@sunnybhakta unable to see the screenshot

**Comment by sunnybhakta** [comment]
Sorry for wrong screenshot url
Here is link for new http://awesomescreenshot.com/0ab4tc1wd0
Thanks.

**Comment by tonydspaniard** [comment]
The problem is on the action that returns the result

**Comment by sunnybhakta** [comment]
Thanks for you answer, But how can i return the proper result from action. Is there any tutorial to work with controller(action) to get proper result.
Thanks

**Comment by tonydspaniard** [comment]
Here https://github.com/2amigos/yii2-file-upload-widget/issues/7
