### ISSUE TITLE
load-image.min.js not found

### ISSUE THREAD

**Issue by reuhtte** [2amigos/yii2-file-upload-widget#27]
This file does not exist in vendor/bower/blueimp-load-image/js. 

I am using yii2-file-upload-widget last release 1.0.1

![upload files - google chrome_007](https://cloud.githubusercontent.com/assets/2817597/7141617/9647f6e2-e298-11e4-9b57-126bf50ed30c.png)

**Comment by creocoder** [comment]
Fixed by #26
