### ISSUE TITLE
i have a question?

### ISSUE THREAD

**Issue by hexl** [2amigos/yii2-file-upload-widget#28]
How can i do this?
1.I have a form with fields: sender, reciver, message, attachment.
2.How can i submit this form with attachment like email does.

**Comment by tonydspaniard** [comment]
Thats tricky but doable, not sure this plugin is best suited for this anyway. When you send the user to the page, create an email record and save it to the DB with 'draft' status. That way your loaded media (attachments) will be linked to the 'draft'ed email.
