### ISSUE TITLE
How could i change a form view?

### ISSUE THREAD

**Issue by Diman31** [2amigos/yii2-file-upload-widget#30]
The view is lying here `vendor\2amigos\yii2-file-upload-widget\src\views\form.php`
I can't modify files in `vendor` directory, but I need to modify this view. How could I do that?

**Comment by tonydspaniard** [comment]
Create your own and tell the widget where to find it: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/FileUploadUI.php#L44
