### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by bhanuagarwal** [2amigos/yii2-file-upload-widget#31]
Hi,
when upload done then delete button is showing by writting this lines:
'deleteUrl' => Url::to(['deletefile','id'=>$image->name]),
 'deleteType' => 'POST',
in controller action i create deletefile action like that:
 public function actionDeletefile($id){
        unlink(Yii::$app->basePath. '/web/uploads/'.$id);
    }
this method delete successfully from folder but delete button is still showing there how i remove it also. plz suggest me!

**Comment by tonydspaniard** [comment]
@bhanuagarwal https://github.com/2amigos/yii2-file-upload-widget/blob/master/README.md#usage
