### ISSUE TITLE
Basic Uploader

### ISSUE THREAD

**Issue by osCMattiFinn** [2amigos/yii2-file-upload-widget#37]
The basic uploader only displays an ordinary file input, rather than the nice upload button.

**Comment by osCMattiFinn** [comment]
It also fails to display a progress bar..... nada

**Comment by hector-del-rio** [comment]
Same here. 

Neither works basicPlus version, it only displays a regular file input.

**Comment by tonydspaniard** [comment]
@osCMattiFinn @hector-del-rio I need more information. Can you please, add your code making sure you work with latest version?

**Comment by kategee** [comment]
I see a bootstrap button, but the basic example does not render a progress bar:

```
<?= FileUpload::widget([
    'model' => $model,
    'attribute' => 'image',
    'url' => ['media/upload', 'id' => $model->id], // your url, this is just for demo purposes,
    'options' => ['accept' => 'image/*'],
    'clientOptions' => [
        'maxFileSize' => 2000000
    ],
    // Also, you can specify jQuery-File-Upload events
    // see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options
    'clientEvents' => [
        'fileuploaddone' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
        'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
    ],
]);?>
```
Renders only:
<img width="778" alt="screen shot 2016-11-07 at 3 56 54 pm" src="https://cloud.githubusercontent.com/assets/3019634/20075612/e0efba3a-a502-11e6-98c9-cefc57b751ea.png">

**Comment by tonydspaniard** [comment]
@kategee  you need to code it your self: 

```php 
<?= FileUpload::widget([
     // ...
    'clientEvents' => [
        'fileuploaddone' => 'function (e, data) {
            $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo('#files'); // do whatever when uploaded
            });
        }',
        'fileuploadprogressall' => 'function(e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .progress-bar').css( // HERE!!!! TO YOUR PROGRESS BAR
                'width',
                progress + '%'
            );
       }',
    ],
]);?>
<!-- The global progress bar -->
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <div id="files" class="files"></div>
```

**Comment by kategee** [comment]
Ok so does this widget only skin the file input? Since you have to code your own progress bar, max file size, uploads, error handling etc?

**Comment by tonydspaniard** [comment]
@kategee it comes with three versions with one where you have to override views if you wish different functionality. If I was to update progress bars would force me to override events that you may use, thus restricting the programming freedom of your development.  I don't think at all that the widget should restrict whatsoever developers decisions. 

Is not simply skinning the file input, it auto registers assets, provides the views for the plugin, actions to handle your file uploads and a very easy way to inject the jquery plugin through a PHP wrapper.

**Comment by kategee** [comment]
Great thanks for clarifying!

**Comment by arifsami03** [comment]
@tonydspaniard 
thanks it works for me
