### ISSUE TITLE
don't show preview

### ISSUE THREAD

**Issue by toanyen** [2amigos/yii2-file-upload-widget#38]
my code
<?= FileUploadUI::widget([
    'model' => $model,
    'attribute' => 'creative_images',
    'url' => ['media/upload'],
    'gallery' => false,
    'fieldOptions' => [
            'accept' => 'image/*'
    ],
    'clientOptions' => [
            'maxFileSize' => 2000000
    ],
    // ...
    'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
    ],
]);
?>

but when i add file. nothing image show preview.

Thanks alot

**Comment by hexl** [comment]
You can just change the form view (file form.php) from ActiveForm to div

**Comment by tonydspaniard** [comment]
too old...
