### ISSUE TITLE
Stray character

### ISSUE THREAD

**Issue by osCMattiFinn** [2amigos/yii2-file-upload-widget#39]
There is a stray semicolon somewhere in this.  When viewing page source the uploader shows this:

;jQuery('#w0').fileupload({"maxFileSize":2000000,"url":"/index.php?r=compressor-defect%2Fupload&id=30"});

Notice the semicolon at the beginning of the line?

This causes both the uploader and following Javascript to fail.

**Comment by tonydspaniard** [comment]
@osCMattiFinn the semicolon should not be an issue. As you can even write this in javascript: 

```js 
;;;;;;;;;;;;;;;;;;;;;;;jQuery... 
```

The semicolon is there for security purposes in case you minify your js.
