### ISSUE TITLE
Upload other file types as .zip , .rar

### ISSUE THREAD

**Issue by levanlau** [2amigos/yii2-file-upload-widget#41]
Hi,
I have used the widget upload image files successfully.
But I can not upload .zip, .rar files.
So, How must i config the widget to handle this ?
Thanks.

**Comment by kapelan** [comment]
In configuration add:

'options' => ['accept' => ''],

and you have to set in field 'accept' proper mime types:

.rar    application/x-rar-compressed, application/octet-stream
.zip    application/zip, application/octet-stream

probably as array

**Comment by levanlau** [comment]
Thanks.
I have configed :
'options' => ['accept' => ['application/x-rar-compressed,
application/octet-stream','application/zip, application/octet-stream']],
But the error still happen ?

**Comment by kapelan** [comment]
Maybe try to split mime types:
'application/x-rar-compressed,
application/octet-stream'

to

'application/x-rar-compressed',
'application/octet-stream'

I'm not sure it will work , but try to use only application/zip and then try to upload zip file.
My advices: 
look into source, analyze source code, don't afraid to play with code and try diffrent possibilites.
It always helps.

And remember PHP mime-types interpretator is not perfect. For example it was telling me the csv's file mime type is application/octet-stream. Good luck

**Comment by levanlau** [comment]
Thanks.
