### ISSUE TITLE
Basic and BasicPlus version only displays a regular file input

### ISSUE THREAD

**Issue by hector-del-rio** [2amigos/yii2-file-upload-widget#47]
Both Basic and BasicPlus versions seem to be broken since they only display a regular file input which does not work properly neither.

**Comment by tonydspaniard** [comment]
I need more information as it works perfectly on our end.

https://github.com/2amigos/yii2-file-upload-widget/issues/82#issuecomment-249776062

**Comment by lllito** [comment]
the same to me my code is above ~
i just display the upload button 
`<?php 
use kartik\form\ActiveForm;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use dosamigos\fileupload\FileUpload;
use dosamigos\fileupload\FileUploadUI;
$this->title = '上传文档';
echo Html::errorSummary($model);

?>
<div class="modal fade" id="document">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><?=$this->title?></h4>
      </div>
      
      
       <?php $form = ActiveForm::begin(
            [
                'action'=>['document/create'],
                'options'=>['enctype'=>'multipart/form-data','class' => 'form-horizontal'],
                'fieldConfig' => [  //统一修改字段的模板
                    'template' => "<div class=\"form-group\">{label}\n<div class=\"col-lg-8\">{input}</div>\n<div class=\"col-lg-2\">{error}</div></div>",
                    //修改显示内容默认为{label}\n{input}\n{hint}\n{error}  \n是html代码显示时的换行
                    'labelOptions' => ['class' => 'col-lg-2 control-label'],  //修改label的样式
                ],
            ]
        ); ?>
      <div class="modal-body">
      <div class="box-body form-horizontal">       
         <?= $form->field($model, 'category_id')->dropDownList(ArrayHelper::map($documentcateogry,'id','mctitle'),['prompt'=>'请选择文档类型']) ?>
         <?= $form->field($model, 'dtitle')->textInput(['maxlength' => true]) ?>
         <?= $form->field($model, 'filepath')->fileInput(['maxlength' => true]) ?>
         <?= $form->field($model, 'remark')->textarea() ?>
         
         
         <?= FileUpload::widget([
                'model' => $model,
                'attribute' => 'filepath',
                'url' => ['media/upload', 'id' => $model->id], // your url, this is just for demo purposes,
                'clientOptions' => [
                    'maxFileSize' => 2000000
                ],
                // Also, you can specify jQuery-File-Upload events
                // see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options
                'clientEvents' => [
                    'fileuploaddone' => 'function(e, data) {
                                            console.log(e);
                                            console.log(data);
                                        }',
                    'fileuploadfail' => 'function(e, data) {
                                            console.log(e);
                                            console.log(data);
                                        }',
                ],
            ]);?>
         
         
         <?=Html::hiddenInput('tid',$tid)?>
        </div>
      </div>
      <div class="modal-footer">
          <?= Html::submitButton($model->isNewRecord ? '创建' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success submit' : 'btn btn-primary']) ?>
         
          <?php ActiveForm::end(); ?>
      </div>
    </div>
    
  </div> 
    
</div>
`

**Comment by tonydspaniard** [comment]
@lllito what do you want to display the full display UI or the basic (select files) button? If you display the latest, you will have to programmatically update your UI like I state here: https://github.com/2amigos/yii2-file-upload-widget/issues/37#issuecomment-259663516 

If you wish the full UI upload you will have to use the other widget.
