### ISSUE TITLE
Progress callback

### ISSUE THREAD

**Issue by usualdesigner** [2amigos/yii2-file-upload-widget#51]
Looks like fileuploadprogress() function doesn't works properly in the 'basic' widget. It works fine in the UI widget only.

Example:
```
'fileuploadprogressall' => 'function(e, data) {
    console.log(parseInt(data.loaded / data.total * 100, 10));
}',
```

Console return value '100' once right after uploading started.

**Comment by tonydspaniard** [comment]
I really need to update the plugin :(

**Comment by kasoft** [comment]
Also in the FileUpload (without UI) the image is not displayed after upload. The UI Version is working. An Update would be realy nice ...

**Comment by tonydspaniard** [comment]
Version was updated
