### ISSUE TITLE
acceptFileTypes return error in FileUploadUI

### ISSUE THREAD

**Issue by momone83** [2amigos/yii2-file-upload-widget#52]
Hi. The widget works properly in all its functions but if I try to set the "acceptFileTypes" parameter in this way

**'acceptFileTypes' => '/(\.|\/)(gif|jpe?g|png)$/i',**

I receive this javascript error

**TypeError: options.acceptFileTypes.test is not a function**

in the browser's console.

If I'm not mistaken the **test()** method tests for a match in a string.
It seems that the regex is not valid.

Can you help me please?

I hope I'm making myself clear.
Thank you.

PS. I tried to validate the files in other way (through the "add" event) with success but I would know why the parameter doesn't work as described in the documentation (https://github.com/blueimp/jQuery-File-Upload/wiki/Options).

**Comment by sandy0201** [comment]
Hi, 

I'm getting the same error too. 
Please assist urgently.

Thank you.

**Comment by Tavousi** [comment]
Hi,

Me too !

**Comment by tonydspaniard** [comment]
It seems is due to the version used. That version is not on version 9.9. Will update as soon as I have some time, or maybe you guys can do a PR? 

The only thing we need to do is to change the version and make sure everything works as expected: https://github.com/2amigos/yii2-file-upload-widget/blob/master/composer.json#L32 should be 9.9.* 

Can you try @Tavousi ? Thanks in advance!

**Comment by tonydspaniard** [comment]
was updated

**Comment by robov** [comment]
when i set these options:
```
    'clientOptions' => [
        'maxNumberOfFiles' => 2,    
        'acceptFileTypes' => '/(\.|\/)(gif|jpe?g|png)$/i',
    ],
```
then I get errors
```
 TypeError: options.acceptFileTypes.test is not a function
```

**Comment by tonydspaniard** [comment]
See my comment on https://github.com/2amigos/yii2-file-upload-widget/issues/116#issuecomment-325190725

**Comment by quevon24** [comment]
If you get here because you got the same error in jquery, pass the regex this way:

'acceptFileTypes' => new RegExp("(\.|\/)(gif|jpe?g|png)$" ,"i")
