### ISSUE TITLE
Multiple Use

### ISSUE THREAD

**Issue by skony20** [2amigos/yii2-file-upload-widget#57]
Is posible to multiple use on the same page 
I found on blueimp this: https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Upload-Widgets-on-the-same-page
but i don't know what and where change in your script.

**Comment by tonydspaniard** [comment]
The use of this widget is to simplify the inclusion of blue imp scripts for one uploader. For advance usages, I highly recommend you to go the js script way (I always do). Register the main scripts whether with yii or directly in your pages and follow that tutorial. Is much better.
