### ISSUE TITLE
Possibility to change view in FileUpload widget

### ISSUE THREAD

**Issue by iushev** [2amigos/yii2-file-upload-widget#60]
FileUpload renders view named `uploadButton`. Name of view should be property to can change in need.

**Comment by invaderhd** [comment]
Yes I agree, I also think we should can disable this render. In my case I want to put the upload button in a different place so I want to use the FileUpload without any button and add my own.

**Comment by tonydspaniard** [comment]
re #17

**Comment by tonydspaniard** [comment]
Is done
