### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by linil** [2amigos/yii2-file-upload-widget#61]
I have tried to complete the setup with no success.
I keep getting Error SyntaxError: Unexpected end of input.
Is there a workaround, or is there something I am missing?

**Comment by barilee** [comment]
Hello,
I face the same problem.
Has anyone fixed this, please?

**Comment by tonydspaniard** [comment]
@linil @barilee without code is very hard to figure out. Do you mind posting your code here? Thanks.

**Comment by uguranyum** [comment]
in this line

 $imageFile = UploadedFile::getInstanceByName('Transport[name]');

Change this Transport[name]

**Comment by tonydspaniard** [comment]
Please, check here: https://github.com/2amigos/yii2-file-upload-widget/tree/master/src/actions 

Not yet tested but will provide you a clear idea of the actions to work with.
