### ISSUE TITLE
Possiblitity to disable rendering the button on FileUpload

### ISSUE THREAD

**Issue by invaderhd** [2amigos/yii2-file-upload-widget#62]
In your last version you change the function run in FileUpload.php now the Upload Button is added automatically, please create a configuration to disable or enable it.

In some situations we want to create our own buttons in a different location. It's a quick to fix this.

```
/**
     * @inheritdoc
     */
    public function run()
    {
        $input = $this->hasModel()
            ? Html::activeFileInput($this->model, $this->attribute, $this->options)
            : Html::fileInput($this->name, $this->value, $this->options);

        echo $this->render('uploadButton', ['input' => $input]);

        $this->registerClientScript();
    }
```

Thank you and keep de good work

**Comment by tonydspaniard** [comment]
do you mind creating a PR? I will merge it...

**Comment by marqu3s** [comment]
I had just sent a PR for this because I also need it.

**Comment by tonydspaniard** [comment]
Where?

**Comment by marqu3s** [comment]
I'm sorry, I think I made a PR to my self... kkkk hold on.

**Comment by marqu3s** [comment]
I think I did it correct now.

**Comment by marqu3s** [comment]
Hi @tonydspaniard!
Please don't forget to check my PR when you have some time.
Thanks!

**Comment by tonydspaniard** [comment]
done on master
