### ISSUE TITLE
Image attribute in post returns empty

### ISSUE THREAD

**Issue by kategee** [2amigos/yii2-file-upload-widget#63]
Using the super basic version, the upload of the file happens and all is good. However when trying to save the model to which the widget is attached, in this case its called `Item` the `image` attribute always returns empty. I would expect that the hidden field value would be populated with the image name after the upload is successful, but the value is empty. Am I missing something?

Widget:

```
<?= FileUpload::widget( [
 	'model'         => $model,
 	'attribute'     => 'image',
 	'url'           => [ 'media/upload', 'id' => $model->item_id ],
 	'options'       => [ 'accept' => 'image/*' ],
 	'clientOptions' => [
 		'maxFileSize' => 2000000,
 		'multiple' => false,
 		'maxNumberOfFiles' => 1,
 	]
 ] ); ?>
```

**Comment by tonydspaniard** [comment]
the "image" should be filled with `UploadedFile::getInstance("image")` and then update your attribute accordingly. I normally use two different attributes with different rules. One for upload, the other for saving. So, the attribute i use for upload is not affecting the other rules.

**Comment by kategee** [comment]
Hmmm... `UploadedFile::getInstance("image")` throws an exception `Missing argument 2 for yii\web\UploadedFile::getInstance()`, and `UploadedFile::getInstanceByName("image")` returns nothing

This is in the ItemController in the create action

**Comment by tonydspaniard** [comment]
@kategee it was an example, you need to use `UploadedFile::getInstance` correctly: 

```php 
UploadedFile::getInstance($model, 'image'); // YOU NEED TO PASS THE MODEL
```

**Comment by kategee** [comment]
Strange, its still returning empty...

**Comment by kategee** [comment]
So I took out the widget and used a regular `<?= $form->field($model, 'image')->fileInput() ?>` and that works fine, and returns an instance. Doing more digging

**Comment by nsept** [comment]
the same problem I have.

**Comment by tonydspaniard** [comment]
@nsept what are your rules?

**Comment by nsept** [comment]
Sorry. Late to delete my post =) It works with:
``` php
UploadedFile::getInstance($model, 'image'); // YOU NEED TO PASS THE MODEL
```
Thanx.

**Comment by kategee** [comment]
@nsept did you get this to work? I still can't get the hidden value in the controller. It doesn't seem to be populating at all...

**Comment by tonydspaniard** [comment]
@kategee do you mind showing your form? Is it set to `multipart/form-data`?

**Comment by kategee** [comment]
```
<div class="photos-form">
	<?php
	$form = ActiveForm::begin( [ 'options' => [ 'enctype' => 'multipart/form-data' ] ] );
	?>
	<?= FileUploadUI::widget([
		'model' => $model,
		'attribute' => 'uploaded_photos',
		'url' => ['media/image-upload', 'id' => $listing_id],
		'gallery' => false,
		'fieldOptions' => [
			'accept' => 'image/*'
		],
		'clientOptions' => [
			'maxFileSize' => 2000000
		],
		// ...
		'clientEvents' => [
			'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
			'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
		],
	]);
	?>
	<div class="form-group" id="btn_save">
		<?= Html::submitButton( 'Save Photos', [ 'class' => 'btn btn-primary' ] ) ?>
	</div>
	<?php ActiveForm::end(); ?>
</div>
```

Just to be clear, the widget uploads the photos fine and the images are in a temp folder. But then when saving the form with the uploaded images, there is no data in the form. I would have assumed that the json output from the upload be saved into a hidden .

Uploaded images:
![screen shot 2016-09-26 at 8 48 44 am](https://cloud.githubusercontent.com/assets/3019634/18834847/3559240c-83c6-11e6-9446-275cb748d99e.png)

But the hidden field has no value:
<img width="393" alt="screen shot 2016-09-26 at 8 49 23 am" src="https://cloud.githubusercontent.com/assets/3019634/18834852/3dadcd6a-83c6-11e6-9bca-45c0eacc7316.png">

So when I press "Save Photos" I don't have access to the data of where the temp photos are stored.

**Comment by tonydspaniard** [comment]
@kategee you need to remove that hidden field. Of course the hidden input has no values. The whole upload of images and rendering after  upload is taken care by the jquery plugin itself. If you wish to display what was uploaded you need to put them on another section: one for uploading media and another to upload. 

When  you submit the pictures, you need to also point their uploaded source (url) to the model and then on the other section being able to display them or manage. Here is an example #82 

uploaded_photos is an attribute for you to upload. I highly recommend to use: 

- this : a different model (Picture - if you work with pictures of course) that would hold the source string of the uploaded image + the relation to the model, the `uploaded_photos` will be used only for file uploads and validating their submissions -ie ensuring file is of a certain size, type, etc
- or : use the attribute to upload the images and then make sure is a string containing all the images src.

**Comment by tonydspaniard** [comment]
@kategee i have added some helper actions on `master branch`, I haven't yet had the time to test them properly but will give you an idea of the three actions required to work with the extension.

**Comment by akbarkhawaja** [comment]
@tonydspaniard I am facing the same issue as @kategee mentioned above. I have a Post model that has media attribute. When I open a Post for editing, i can see already uploaded image. When i hit Update button, my media attribute sets to empty string, since media attribute is being sent empty on updating the record
