### ISSUE TITLE
ver 1.0.4 Error

### ISSUE THREAD

**Issue by shorttimer2** [2amigos/yii2-file-upload-widget#65]
verison 1.0.4 gives an error message Error: cannot call methods on fileupload prior to initialization; attempted to call method 'option'
ver. 1.0.1 - ok

**Comment by tonydspaniard** [comment]
Do you mind sharing your code? thanks!

**Comment by shorttimer2** [comment]
I think the error code in the updated plugin Jquery File Upload...

/* view */
use dosamigos\fileupload\FileUploadUI;
use yii\helpers\Url;
use yii\helpers\Html;

$idobject = '0';
if(isset($model->id_object))
	$idobject = $model->id_object;

//Here I get the data already uploaded photos.
$script = "		
		jQuery.ajax({
                url: '/index.php?r=cabinet/photos/read&id=" . $idobject ."',
                dataType: 'json',
                type:   'post',
                context: jQuery('#photos-name-form')[0]
            }).done(function (result) {
            console.log(result);
                jQuery(this).fileupload('option', 'done').call(this, jQuery.Event('done'), {result: result});/* this string - Error: cannot call methods on fileupload prior to initialization; attempted to call method 'option' */
            });
		";

$this->registerJs($script);

<?= FileUploadUI::widget([
    'model' => $model,
    'attribute' => 'name[]',
    'url' => ['photos/upload', 'id' => $idobject],
    'gallery' => false,
    'fieldOptions' => [
            'accept' => 'image/*',
    ],
    'clientOptions' => [
            'maxFileSize' => 2000000
    ],
    // ...
    'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
    ],
]);
/* ajax read controller */
public function actionRead($id)
    {
    	$object  = ObjectForm::findOne($id);
    	
    	
    	$model = new Photos();
    	$response = Yii::$app->response;
    	$response->getHeaders()->set('Vary', 'Accept');
    	$response->format = \yii\web\Response::FORMAT_JSON;
    	$photoarr = $model->find()
    	->where(['id_object' => $id])
    	->asArray()
    	->all();
    	$responsearr = array();
    	foreach ($photoarr as $photo)
    	{
    		$photo_main = ($object->id_photo_main == $photo['id']) ? true :false;		
    		$responsearr['files'][] = $this->createResponce($photo,$photo_main);
    	}
    	$response->data = $responsearr;
    	return $response;  	 
    }
/* Create responce */
private function createResponce($file,$photo_main = false) 
	{		
		$responce['name'] = $file['name'];
		$responce['type'] = 'image/*';
		$responce['size'] = $file['size'];
		$responce['url']  = ['/images/'. $file['id_object']. '/' . $file['name']];
		$responce['thumbnailUrl'] = Url::to('/images/'. $file['id_object']. '/thumb/' . $file['name'],true);                                   ;
		$responce['deleteUrl'] = Url::to(['deletefile', 'id' => $file['id']]);
		$responce['deleteType'] =  'POST';
		if(!$photo_main)
		{
			$responce['photoMain'] = Url::to(['set', 'id' => $file['id']]);
		}
		else
		{
		$responce['photoMain'] = false;
		}
		return $responce;
	}

**Comment by tonydspaniard** [comment]
The problem is not with the widget itself. You need to append that script AFTER the widget.  Also, I am not sure the code is correct. I would simply render the ones uploaded, why an ajax call?

**Comment by shorttimer2** [comment]
I think the error code in the updated plugin Jquery File Upload...

/* view */
use dosamigos\fileupload\FileUploadUI;
use yii\helpers\Url;
use yii\helpers\Html;

$idobject = '0';
if(isset($model->id_object))
	$idobject = $model->id_object;

//Here I get the data already uploaded photos.
$script = "		
		jQuery.ajax({
                url: '/index.php?r=cabinet/photos/read&id=" . $idobject ."',
                dataType: 'json',
                type:   'post',
                context: jQuery('#photos-name-form')[0]
            }).done(function (result) {
            console.log(result);
                jQuery(this).fileupload('option', 'done').call(this, jQuery.Event('done'), {result: result});/* this string - Error: cannot call methods on fileupload prior to initialization; attempted to call method 'option' */
            });
		";

$this->registerJs($script);

<?= FileUploadUI::widget([
    'model' => $model,
    'attribute' => 'name[]',
    'url' => ['photos/upload', 'id' => $idobject],
    'gallery' => false,
    'fieldOptions' => [
            'accept' => 'image/*',
    ],
    'clientOptions' => [
            'maxFileSize' => 2000000
    ],
    // ...
    'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
    ],
]);
/* ajax read controller */
public function actionRead($id)
    {
    	$object  = ObjectForm::findOne($id);
    	
    	
    	$model = new Photos();
    	$response = Yii::$app->response;
    	$response->getHeaders()->set('Vary', 'Accept');
    	$response->format = \yii\web\Response::FORMAT_JSON;
    	$photoarr = $model->find()
    	->where(['id_object' => $id])
    	->asArray()
    	->all();
    	$responsearr = array();
    	foreach ($photoarr as $photo)
    	{
    		$photo_main = ($object->id_photo_main == $photo['id']) ? true :false;		
    		$responsearr['files'][] = $this->createResponce($photo,$photo_main);
    	}
    	$response->data = $responsearr;
    	return $response;  	 
    }
/* Create responce */
private function createResponce($file,$photo_main = false) 
	{		
		$responce['name'] = $file['name'];
		$responce['type'] = 'image/*';
		$responce['size'] = $file['size'];
		$responce['url']  = ['/images/'. $file['id_object']. '/' . $file['name']];
		$responce['thumbnailUrl'] = Url::to('/images/'. $file['id_object']. '/thumb/' . $file['name'],true);                                   ;
		$responce['deleteUrl'] = Url::to(['deletefile', 'id' => $file['id']]);
		$responce['deleteType'] =  'POST';
		if(!$photo_main)
		{
			$responce['photoMain'] = Url::to(['set', 'id' => $file['id']]);
		}
		else
		{
		$responce['photoMain'] = false;
		}
		return $responce;
	}

**Comment by shorttimer2** [comment]
When I do render the widget, I need it to have data already loaded photo. I get the data using ajax. Most likely the problem in an updated version of the plugin Jquery File Upload, which uses the widget. I did not see what version uses a widget 1.0.1 and 1.0.4 which. I have a big project and there is no time to deal. In the old version it works just fine. Simply lock the version 1.0.1 in the Composer.

**Comment by shorttimer2** [comment]
Version 1.0.1 works fine. Only need to replace the line 26 of FileUploadAccept.php.
It 'blueimp-load-image/js/load-image.min.js',
So 'blueimp-load-image/js/**load-image.all.min.js**',
Because there is no load-image.min.js file, instead load-image.all.min.js
Maybe someone can help ...

**Comment by tonydspaniard** [comment]
That is corrected on master: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/BlueimpLoadImageAsset.php
