### ISSUE TITLE
Error Messge from Model

### ISSUE THREAD

**Issue by Julian-B90** [2amigos/yii2-file-upload-widget#68]
How can i show the Error message from my model?

I have an model that save the path string from the file and that model don´t show the errors.

**Comment by Ultmat5** [comment]
if the file did not pass the validation returns an error
return Json::encode([
                        'files' => [[
                           'error' => "Error message",
                        ]]
                    ]);

**Comment by tonydspaniard** [comment]
Thanks @Ultmat5

**Comment by tonydspaniard** [comment]
Check here, not yet tested but will give you an idea: https://github.com/2amigos/yii2-file-upload-widget/tree/master/src/actions
