### ISSUE TITLE
Right way to change template

### ISSUE THREAD

**Issue by brain2xml** [2amigos/yii2-file-upload-widget#72]
Hi!
It's good widget, thanks for it!

I want little change template. I changed file vendor/2amigos/yii2-file-upload-widget/src/views/download.php but wory about composer update, my changes can be lost? Is there better way to change template?

**Comment by davidtim** [comment]
In my case, I create view in that directory for example "test.php". Then in code
`FileUploadUI::widget([
                'model' => $model,
                'attribute' => 'image',
                'url' => ['page/upload-image', 'id' => $model->id],
                'gallery' => false,
                'uploadTemplateView' => 'test',
                'fieldOptions' => [
                    'accept' => 'image/*'
                ],
                'clientOptions' => [
                    'maxFileSize' => 2000000
                ],
                'clientEvents' => [
                    'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
//                    'fileuploadfail' => 'function(e, data) {
//                                    console.log(e);
//                                    console.log(data);
//                                }',
                ],
            ]);`

**Comment by brain2xml** [comment]
thanks

**Comment by becksonq** [comment]
I create view file template-download.php in 'frontend/views/adverts/'
In code i use 'downloadTemplateView' => 'path/to/my/view'

```
FileUploadUI::widget( [
            'model'         => $images,
            'attribute'     => 'images',          
            'gallery'       => false,

            'downloadTemplateId' => null,
            'downloadTemplateView' => '@frontend/views/adverts/template-download',

            'fieldOptions'  => [
                'accept' => 'image/*'
            ],
            'clientOptions' => [
                'maxFileSize'      => 2000000,
            ],
            'clientEvents'  => [
              ...
            ],
        ] );
```
