### ISSUE TITLE
Yii::t shouldn't use 'app' as message category

### ISSUE THREAD

**Issue by theinspire** [2amigos/yii2-file-upload-widget#73]
This construction in src/views/uploadButton.phpuploadButton.php
`<span><?= Yii::t('app', 'Select file...') ?></span>`
generates exception every time when FileUpload::run() execute if there is no the 'app' message category.

Probably, 'fileupload' message category is more suitable in this case.

**Comment by tonydspaniard** [comment]
I will add its very own translations... thanks
