### ISSUE TITLE
blueimp-file-upload no matching package found.

### ISSUE THREAD

**Issue by ferllings** [2amigos/yii2-file-upload-widget#76]
Hello,

I can't install using composer:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-file-upload-widget 1.0.4 requires bower-asset/blueimp-file-upload ~9.9 -> no matching package found.

**Comment by ferllings** [comment]
Nobody has the same issue

**Comment by tonydspaniard** [comment]
are you doing `composer require 2amigos/yii2-file-upload-widget` ? 

whats your composer version?

**Comment by ferllings** [comment]
Sorry, without any solution I moved to another library.
