### ISSUE TITLE
Uncaught TypeError: jQuery(...).fileupload is not a function

### ISSUE THREAD

**Issue by zplzpl** [2amigos/yii2-file-upload-widget#79]
Uncaught TypeError: jQuery(...).fileupload is not a function

what happen?

**Comment by tonydspaniard** [comment]
assets not registered.

**Comment by billysutomo** [comment]
@tonydspaniard hi tony
im sorry for interrupting, currently im also having this problem
i know that you said the assets is not registered
but i dont get what you mean, maybe you could explain a little more for the solution
thank you before

**Comment by tonydspaniard** [comment]
@billysutomo sometimes we do renderAjax or use a modal window with returned results from the server. Thats one of the reasons why the asset bundle is not registering the assets. Make sure the asset bundle is registered. Without it the fileupload plugin won't be accessible through jQuery.

**Comment by robov** [comment]
I do understand that I need to RE-register the assets when I render the widget through renderAjax. However I do not know HOW to RE-Register the assets ?

**Comment by robov** [comment]
Theplugin is rendered in a pjax container, and when I register the assets in ... or out of the pjax container, it still has the same fileupload not found
