### ISSUE TITLE
pjax not compatible with widget

### ISSUE THREAD

**Issue by UnijayaSaufiyuddin** [2amigos/yii2-file-upload-widget#80]
i'm trying to use pjax with this widget.

my pjax use for listview. if i remove the widget from the page, i can use the listview pagination without refreshing the page, but when i include this widget, the page refresh when i click on the listview pagination.

why?

**Comment by tonydspaniard** [comment]
@UnijayaSaufiyuddin when you use pjax on reload you need to re-set the widget. as the content has been changed. 
The only way to fix this is by adding the initialization of the widget on your pjax events: https://github.com/defunkt/jquery-pjax#pjaxreload
