### ISSUE TITLE
Delete callback

### ISSUE THREAD

**Issue by saini3080** [2amigos/yii2-file-upload-widget#93]
how to get image delete call back from delete image url 
i'm sending the call back from delete action in json format but not able to get it from data

**Comment by tonydspaniard** [comment]
hi @saini3080 do you mind adding some code and explanations on what you are trying to achieve? 

Thanks

**Comment by saini3080** [comment]
my delete function is

public function actionImageDelete($name){
	
		$directory = \Yii::getAlias('@frontend/web/img/temp') . DIRECTORY_SEPARATOR . Yii::$app->session->id;
		
		if (is_file($directory . DIRECTORY_SEPARATOR . $name)) {
			unlink($directory . DIRECTORY_SEPARATOR . $name);
		}
		
		$files = FileHelper::findFiles($directory);
		$output = [];
		foreach ($files as $file){
			$path = Yii::$app->urlManager->createUrl('./../../frontend/web/') . '/img/temp/' . Yii::$app->session->id . DIRECTORY_SEPARATOR . basename($file);
			
			//unlink($path);
			//$output['deleted'] = $path;
			$output['files'][] = [
				'name' => basename($file),
				'size' => filesize($file),
				"url" => $path,
				"thumbnailUrl" => $path,
				"deleteUrl" => Url::to(['image-delete','name'=> basename($file)]), //'image-delete?name=' . basename($file),
				"deleteType" => "POST"
			];
		}
		return Json::encode($output);
	
	}

but in the response of "fileuploaddestroy" im not able to get response same like i sent from here

**Comment by tonydspaniard** [comment]
Why don't you use https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/actions/FileDeleteAction.php ? And if you don't please use same approach. The response belongs to a file only, not an array of files afaik
