### ISSUE TITLE
Подскажите пожалуйста как получить ответ ajax?

### ISSUE THREAD

**Issue by makeloo** [2amigos/yii2-file-upload-widget#96]
От обработчика ответ приходит в виде строки. В дебаггере файрфокса вижу что ответ приходит правильный. Но не пойму как его получить. 
` 'clientEvents' => [
                                        'fileuploaddone' => 'function(e, data) {
                                        myappendto(data); //Моя функция для обработки ответа
                            }',
`
Этот код не работает, так как data содержит не то что приходит. А какой то другой объект.
Как получить ответ обработчика? Спасибо.

**Comment by makeloo** [comment]
уже решил. data.result и все чики пики

**Comment by tonydspaniard** [comment]
English? 👍
