### ISSUE TITLE
Fix dependency on jQuery

### ISSUE THREAD

**Issue by Eseperio** [2amigos/yii2-file-upload-widget#98]
Sometimes plugin does not work because it loads before jQueryAsset. There should be a property to set the assets main dependency. It happens when using different JQuery asset than the included as default in Yii2

**Comment by tonydspaniard** [comment]
That only happens if you use the plugin on partial and your resource is different as you state. I recommend you to create your very own AssetBundle which includes the missing files. Then extend the widget and override the method that registers the bundle.

**Comment by filipajdacic** [comment]
@Eseperio 
You can simply override bundles in your assetManager in your globar config.

For example if you want to remove boostrap plugin dependency you can do in your config.main under components:

```
// ....
        'assetManager'=>[
            'bundles'=>[
                'dosamigos\fileupload\FileUploadUIAsset'=>[
                    //add all css-files of the bundle except the duplicate one here
                    //'js'=>['js/fileA.js', 'js/fileB.js'],
                    'depends' => [        
                        'yii\web\JqueryAsset',
                        //'yii\bootstrap\BootstrapPluginAsset',
                        'dosamigos\fileupload\BlueimpLoadImageAsset',
                        'dosamigos\fileupload\BlueimpCanvasToBlobAsset',
                        'dosamigos\fileupload\BlueimpTmplAsset'
                    ],
                ],
            ],
        ],
// ....
```
