### ISSUE TITLE
Preloaded files

### ISSUE THREAD

**Issue by Nivans** [2amigos/yii2-file-upload-widget#99]
I have to initialize widget with preloaded files, files loaded earlier. How can I pass to the widget array of files?

**Comment by tonydspaniard** [comment]
I do not do that with the widget. What I do is to have a section that has nothing to do with the loaders. That is, create a section with ALREADY LOADED on a tab or after the uploader and provide the option to delete them to the user. Thats the best, trust me.

**Comment by sdelfi** [comment]
Hi.

Sorry, but what I need to preload earlier uploaded files to the widget?
Thanks
